version: '3'

services:
  db:
    container_name: games_pg
    hostname: pg.games.com
    image: postgres:14.2
    environment:
      PGUSER: "games" #Variável pré-definir o usuário da ferramenta psql.
      POSTGRES_USER: "games"
      POSTGRES_PASSWORD: "01234"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 
    networks:
      - games

  
networks: 
  games:
    driver: bridge